In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#reading file
df = pd.read_csv("mcdonalds.csv")
df.head()

yummy	convenient	spicy	fattening	greasy	fast	cheap	tasty	expensive	healthy	disgusting	Like	Age	VisitFrequency	Gender
0	No	Yes	No	Yes	No	Yes	Yes	No	Yes	No	No	-3	61	Every three months	Female
1	Yes	Yes	No	Yes	Yes	Yes	Yes	Yes	Yes	No	No	+2	51	Every three months	Female
2	No	Yes	Yes	Yes	Yes	Yes	No	Yes	Yes	Yes	No	+1	62	Every three months	Female
3	Yes	Yes	No	Yes	Yes	Yes	Yes	Yes	No	No	Yes	+4	69	Once a week	Female
4	No	Yes	No	Yes	Yes	Yes	Yes	No	No	Yes	No	+2	49	Once a month	Male
df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1453 entries, 0 to 1452
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   yummy           1453 non-null   object
 1   convenient      1453 non-null   object
 2   spicy           1453 non-null   object
 3   fattening       1453 non-null   object
 4   greasy          1453 non-null   object
 5   fast            1453 non-null   object
 6   cheap           1453 non-null   object
 7   tasty           1453 non-null   object
 8   expensive       1453 non-null   object
 9   healthy         1453 non-null   object
 10  disgusting      1453 non-null   object
 11  Like            1453 non-null   object
 12  Age             1453 non-null   int64 
 13  VisitFrequency  1453 non-null   object
 14  Gender          1453 non-null   object
dtypes: int64(1), object(14)
memory usage: 170.4+ KB
df.shape
(1453, 15)
df.describe()
Age
count	1453.000000
mean	44.604955
std	14.221178
min	18.000000
25%	33.000000
50%	45.000000
75%	57.000000
max	71.000000
df.isna().sum()
yummy             0
convenient        0
spicy             0
fattening         0
greasy            0
fast              0
cheap             0
tasty             0
expensive         0
healthy           0
disgusting        0
Like              0
Age               0
VisitFrequency    0
Gender            0
dtype: int64
#variable counts
df['Gender'].value_counts()
Female    788
Male      665
Name: Gender, dtype: int64
df['VisitFrequency'].value_counts()
Once a month             439
Every three months       342
Once a year              252
Once a week              235
Never                    131
More than once a week     54
Name: VisitFrequency, dtype: int64
df['Like'].value_counts()
+3              229
+2              187
0               169
+4              160
+1              152
I hate it!-5    152
I love it!+5    143
-3               73
-4               71
-2               59
-1               58
Name: Like, dtype: int64
Step 1: Deciding (not) to Segment
Step 2: Specifying the Ideal Target Segment
Step 3: Collecting Data
Step 4: Exploring Data
# Target Segmentation 
#1 Segmenting based on age and gender (Sociodemographic Segmentation)
labels = ['Female', 'Male']
size = df['Gender'].value_counts()
colors = ['orange', 'blue']
explode = [0, 0.1]
plt.rcParams['figure.figsize'] = (7, 7)
plt.pie(size, colors = colors, explode = explode, labels = labels, shadow = True, autopct = '%.2f%%')
plt.title('Gender', fontsize = 20)
plt.axis('off')
plt.legend()
plt.show()
# Percentage proporation of female is customers in more than male customers

# Age based Segmentation
plt.figure(figsize=(15,6))
a = sns.countplot(x = df['Age'])
plt.title('Age based segmentation', fontsize=15)
# Maximum customers of mcdonalds belongs to age group 30-40 and 50-60
Text(0.5, 1.0, 'Age based segmentation')

# Psychographic Segmentation
# Replacing text in Like column with numbered values for convience
df['Like'] = df['Like'].replace({'I hate it!-5': '-5','I love it!+5':'+5'})

sns.barplot(x='Like', y='Age', data=df)
plt.title('Ratings of Mcdonald')
Text(0.5, 1.0, 'Ratings of Mcdonald')

# Label encoding for categorical varibales
# First 11 columns are categorical in nature
from sklearn.preprocessing import LabelEncoder
df_cat = df.iloc[:,0:11]
df_cat
yummy	convenient	spicy	fattening	greasy	fast	cheap	tasty	expensive	healthy	disgusting
0	No	Yes	No	Yes	No	Yes	Yes	No	Yes	No	No
1	Yes	Yes	No	Yes	Yes	Yes	Yes	Yes	Yes	No	No
2	No	Yes	Yes	Yes	Yes	Yes	No	Yes	Yes	Yes	No
3	Yes	Yes	No	Yes	Yes	Yes	Yes	Yes	No	No	Yes
4	No	Yes	No	Yes	Yes	Yes	Yes	No	No	Yes	No
...	...	...	...	...	...	...	...	...	...	...	...
1448	No	Yes	No	Yes	Yes	No	No	No	Yes	No	Yes
1449	Yes	Yes	No	Yes	No	No	Yes	Yes	No	Yes	No
1450	Yes	Yes	No	Yes	No	Yes	No	Yes	Yes	No	No
1451	Yes	Yes	No	No	No	Yes	Yes	Yes	No	Yes	No
1452	No	Yes	No	Yes	Yes	No	No	No	Yes	No	Yes
1453 rows × 11 columns

def labelling(x):
    df[x] = LabelEncoder().fit_transform(df[x])
    return df

df_cat = df.iloc[:,0:11]
for i in df_cat:
    labelling(i)
    
df
yummy	convenient	spicy	fattening	greasy	fast	cheap	tasty	expensive	healthy	disgusting	Like	Age	VisitFrequency	Gender
0	0	1	0	1	0	1	1	0	1	0	0	-3	61	Every three months	Female
1	1	1	0	1	1	1	1	1	1	0	0	+2	51	Every three months	Female
2	0	1	1	1	1	1	0	1	1	1	0	+1	62	Every three months	Female
3	1	1	0	1	1	1	1	1	0	0	1	+4	69	Once a week	Female
4	0	1	0	1	1	1	1	0	0	1	0	+2	49	Once a month	Male
...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...
1448	0	1	0	1	1	0	0	0	1	0	1	-5	47	Once a year	Male
1449	1	1	0	1	0	0	1	1	0	1	0	+2	36	Once a week	Female
1450	1	1	0	1	0	1	0	1	1	0	0	+3	52	Once a month	Female
1451	1	1	0	0	0	1	1	1	0	1	0	+4	41	Every three months	Male
1452	0	1	0	1	1	0	0	0	1	0	1	-3	30	Every three months	Male
1453 rows × 15 columns

# Histogram of the each attributes
plt.rcParams['figure.figsize'] = (12,14)
df.hist()
plt.show()

# Converting 11 categorical columns into array
x = df_cat.values
x
array([[0, 1, 0, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 0],
       [0, 1, 1, ..., 1, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 0, 0],
       [1, 1, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1]])
# Calculating mean of 11 columns
round(df.iloc[:,0:11].mean(),2)
yummy         0.55
convenient    0.91
spicy         0.09
fattening     0.87
greasy        0.53
fast          0.90
cheap         0.60
tasty         0.64
expensive     0.36
healthy       0.20
disgusting    0.24
dtype: float64
PRINCIPAL COMPONENT ANALYSIS
from sklearn.decomposition import PCA
from sklearn import preprocessing
pca_data = preprocessing.scale(x)

pca = PCA(n_components=11)
pc = pca.fit_transform(x)
names = ['pc1','pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10','pc11']
pf= pd.DataFrame(data = pc, columns = names)
pf
pc1	pc2	pc3	pc4	pc5	pc6	pc7	pc8	pc9	pc10	pc11
0	0.425367	-0.219079	0.663255	-0.401300	0.201705	-0.389767	-0.211982	0.163235	0.181007	0.515706	-0.567074
1	-0.218638	0.388190	-0.730827	-0.094724	0.044669	-0.086596	-0.095877	-0.034756	0.111476	0.493313	-0.500440
2	0.375415	0.730435	-0.122040	0.692262	0.839643	-0.687406	0.583112	0.364379	-0.322288	0.061759	0.242741
3	-0.172926	-0.352752	-0.843795	0.206998	-0.681415	-0.036133	-0.054284	-0.231477	-0.028003	-0.250678	-0.051034
4	0.187057	-0.807610	0.028537	0.548332	0.854074	-0.097305	-0.457043	0.171758	-0.074409	0.031897	0.082245
...	...	...	...	...	...	...	...	...	...	...	...
1448	1.550242	0.275031	-0.013737	0.200604	-0.145063	0.306575	-0.075308	0.345552	-0.136589	-0.432798	-0.456076
1449	-0.957339	0.014308	0.303843	0.444350	-0.133690	0.381804	-0.326432	0.878047	-0.304441	-0.247443	-0.193671
1450	-0.185894	1.062662	0.220857	-0.467643	-0.187757	-0.192703	-0.091597	-0.036576	0.038255	0.056518	-0.012800
1451	-1.182064	-0.038570	0.561561	0.701126	0.047645	0.193687	-0.027335	-0.339374	0.022267	-0.002573	-0.105316
1452	1.550242	0.275031	-0.013737	0.200604	-0.145063	0.306575	-0.075308	0.345552	-0.136589	-0.432798	-0.456076
1453 rows × 11 columns

pf.head()
pc1	pc2	pc3	pc4	pc5	pc6	pc7	pc8	pc9	pc10	pc11
0	0.425367	-0.219079	0.663255	-0.401300	0.201705	-0.389767	-0.211982	0.163235	0.181007	0.515706	-0.567074
1	-0.218638	0.388190	-0.730827	-0.094724	0.044669	-0.086596	-0.095877	-0.034756	0.111476	0.493313	-0.500440
2	0.375415	0.730435	-0.122040	0.692262	0.839643	-0.687406	0.583112	0.364379	-0.322288	0.061759	0.242741
3	-0.172926	-0.352752	-0.843795	0.206998	-0.681415	-0.036133	-0.054284	-0.231477	-0.028003	-0.250678	-0.051034
4	0.187057	-0.807610	0.028537	0.548332	0.854074	-0.097305	-0.457043	0.171758	-0.074409	0.031897	0.082245
pf.describe()
pc1	pc2	pc3	pc4	pc5	pc6	pc7	pc8	pc9	pc10	pc11
count	1.453000e+03	1.453000e+03	1.453000e+03	1.453000e+03	1.453000e+03	1.453000e+03	1.453000e+03	1.453000e+03	1.453000e+03	1.453000e+03	1.453000e+03
mean	2.307552e-17	-4.137548e-17	-2.110918e-17	4.322840e-17	4.515773e-17	-3.961808e-17	4.406890e-17	-5.539654e-17	-2.976131e-17	5.616063e-17	1.134674e-17
std	7.570495e-01	6.074556e-01	5.046195e-01	3.987986e-01	3.374050e-01	3.102746e-01	2.896973e-01	2.751220e-01	2.652511e-01	2.488418e-01	2.369028e-01
min	-1.188421e+00	-1.040274e+00	-8.808133e-01	-5.906209e-01	-1.045938e+00	-8.524911e-01	-8.059463e-01	-9.316201e-01	-9.557606e-01	-8.871971e-01	-8.851439e-01
25%	-5.476794e-01	-3.568482e-01	-4.507793e-01	-2.814986e-01	-2.433247e-01	-1.927027e-01	-1.342190e-01	-1.717258e-01	-1.181233e-01	-1.465751e-01	-1.053163e-01
50%	-7.074592e-02	-1.151632e-01	2.687734e-02	-1.163200e-01	3.348785e-02	-3.460184e-02	-6.366220e-02	-3.475619e-02	3.868061e-02	3.020635e-02	-1.201409e-02
75%	4.933012e-01	3.915540e-01	3.515939e-01	2.702298e-01	2.048293e-01	1.747453e-01	2.318357e-02	1.295966e-01	7.987794e-02	7.001416e-02	8.554080e-02
max	1.705573e+00	1.279130e+00	1.326976e+00	1.355278e+00	1.053327e+00	1.323793e+00	1.350886e+00	1.121388e+00	1.086693e+00	1.181524e+00	9.255829e-01
# Proportion of Variance (from PC1 to PC11)
pca.explained_variance_ratio_
array([0.29944723, 0.19279721, 0.13304535, 0.08309578, 0.05948052,
       0.05029956, 0.0438491 , 0.03954779, 0.0367609 , 0.03235329,
       0.02932326])
np.cumsum(pca.explained_variance_ratio_)
array([0.29944723, 0.49224445, 0.6252898 , 0.70838558, 0.7678661 ,
       0.81816566, 0.86201476, 0.90156255, 0.93832345, 0.97067674,
       1.        ])
# Correlation coefficient between original variables and the component

loadings = pca.components_
num_pc = pca.n_features_
pc_list = ["PC"+str(i) for i in list(range(1, num_pc+1))]
loadings_df = pd.DataFrame.from_dict(dict(zip(pc_list, loadings)))
loadings_df['variable'] = df_cat.columns.values
loadings_df = loadings_df.set_index('variable')
loadings_df
PC1	PC2	PC3	PC4	PC5	PC6	PC7	PC8	PC9	PC10	PC11
variable											
yummy	-0.476933	0.363790	-0.304444	0.055162	-0.307535	0.170738	-0.280519	0.013041	0.572403	-0.110284	0.045439
convenient	-0.155332	0.016414	-0.062515	-0.142425	0.277608	-0.347830	-0.059738	-0.113079	-0.018465	-0.665818	-0.541616
spicy	-0.006356	0.018809	-0.037019	0.197619	0.070620	-0.355087	0.707637	0.375934	0.400280	-0.075634	0.141730
fattening	0.116232	-0.034094	-0.322359	-0.354139	-0.073405	-0.406515	-0.385943	0.589622	-0.160512	-0.005338	0.250910
greasy	0.304443	-0.063839	-0.802373	0.253960	0.361399	0.209347	0.036170	-0.138241	-0.002847	0.008707	0.001642
fast	-0.108493	-0.086972	-0.064642	-0.097363	0.107930	-0.594632	-0.086846	-0.627799	0.166197	0.239532	0.339265
cheap	-0.337186	-0.610633	-0.149310	0.118958	-0.128973	-0.103241	-0.040449	0.140060	0.076069	0.428087	-0.489283
tasty	-0.471514	0.307318	-0.287265	-0.002547	-0.210899	-0.076914	0.360453	-0.072792	-0.639086	0.079184	0.019552
expensive	0.329042	0.601286	0.024397	0.067816	-0.003125	-0.261342	-0.068385	0.029539	0.066996	0.454399	-0.490069
healthy	-0.213711	0.076593	0.192051	0.763488	0.287846	-0.178226	-0.349616	0.176303	-0.185572	-0.038117	0.157608
disgusting	0.374753	-0.139656	-0.088571	0.369539	-0.729209	-0.210878	-0.026792	-0.167181	-0.072483	-0.289592	-0.040662
# Correlation matrix plot for loadings 
plt.rcParams['figure.figsize'] = (20,15)
ax = sns.heatmap(loadings_df, annot=True, cmap='inferno')
plt.show()

# Scree plot (Elbow test) - PCA
from bioinfokit.visuz import cluster
cluster.screeplot(obj=[pc_list, pca.explained_variance_ratio_],show=True,dim=(10,5))

plt.scatter(pf.pc1, pf.pc2)
plt.title('PC1 against PC2')
plt.xlabel('PC1')
plt.ylabel('PC2')
Text(0, 0.5, 'PC2')

# Get PC scores
pca_scores = PCA().fit_transform(x)

# Get 2D biplot
cluster.biplot(cscore=pca_scores, loadings=loadings, labels=df.columns.values, var1=round(pca.explained_variance_ratio_[0]*100, 2),
    var2=round(pca.explained_variance_ratio_[1]*100, 2),show=True,dim=(10,5))

Step 5: Extracting Segments
# Using k-means clustering analysis
from sklearn.utils.metaestimators import available_if
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer
model = KMeans()
visualizer = KElbowVisualizer(model, k=(1,12)).fit(df_cat)
visualizer.show()

<AxesSubplot:title={'center':'Distortion Score Elbow for KMeans Clustering'}, xlabel='k', ylabel='distortion score'>
# K-means Clustering 

kmeans = KMeans(n_clusters=4, init='k-means++', random_state=0).fit(df_cat)
df['cluster_num'] = kmeans.labels_ # Adding to df
print (kmeans.labels_) # Label assigned for each data point
print (kmeans.inertia_) # Gives within-cluster sum of squares. 
print(kmeans.n_iter_) # Number of iterations that k-means algorithm runs to get a minimum within-cluster sum of squares
print(kmeans.cluster_centers_) # Location of the centroids on each cluster.
[2 0 0 ... 0 1 3]
1603.0604440558945
7
[[0.85448916 0.9628483  0.13312693 0.90712074 0.61919505 0.86068111
  0.10835913 0.93188854 0.89783282 0.20433437 0.10526316]
 [0.88793103 0.98103448 0.0862069  0.79482759 0.32931034 0.96034483
  0.92241379 0.97586207 0.01724138 0.32068966 0.04310345]
 [0.02302632 0.89144737 0.07236842 0.92434211 0.66776316 0.96381579
  0.93421053 0.15460526 0.01315789 0.07236842 0.38815789]
 [0.0203252  0.68292683 0.08536585 0.91463415 0.69512195 0.73170732
  0.06504065 0.08943089 0.87804878 0.06097561 0.71544715]]
# To see each cluster size
from collections import Counter
Counter(kmeans.labels_)
Counter({2: 304, 0: 323, 1: 580, 3: 246})
# Visulazing clusters
sns.scatterplot(data=pf, x="pc1", y="pc2", hue=kmeans.labels_)
plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], 
            marker="X", c="r", s=80, label="centroids")
plt.legend()
plt.show()

# Hierarchical Clustering Algorithm
# Create demogram and find the best clustering value
from scipy.cluster.hierarchy import linkage, dendrogram

merg = linkage(df_cat, method='ward')
plt.rcParams['figure.figsize'] = (25,10)
dendrogram(merg,leaf_rotation = 90)
plt.xlabel("data points", fontsize = 15)
plt.ylabel("euclidean distance", fontsize=15)
plt.show()

Step 7: Describing Segments
# Describing Segments

from statsmodels.graphics.mosaicplot import mosaic
from itertools import product

crosstab =pd.crosstab(df['cluster_num'],df['Like'])
# Reordering cols
crosstab = crosstab[['-5','-4','-3','-2','-1','0','+1','+2','+3','+4','+5']]
crosstab 
Like	-5	-4	-3	-2	-1	0	+1	+2	+3	+4	+5
cluster_num											
0	5	3	7	6	7	36	42	60	66	47	44
1	4	4	2	6	13	43	65	90	143	111	99
2	54	36	34	28	25	51	31	31	12	2	0
3	89	28	30	19	13	39	14	6	8	0	0
plt.rcParams['figure.figsize'] = (7,5)
mosaic(crosstab.stack())
plt.show()

# Mosaic plot gender vs segment
crosstab_gender =pd.crosstab(df['cluster_num'],df['Gender'])
crosstab_gender
Gender	Female	Male
cluster_num		
0	154	169
1	349	231
2	179	125
3	106	140
plt.rcParams['figure.figsize'] = (7,5)
mosaic(crosstab_gender.stack())
plt.show()

# Box plot for age

sns.boxplot(x="cluster_num", y="Age", data=df)
<AxesSubplot:xlabel='cluster_num', ylabel='Age'>

Step 8: Selecting the targets segments
# Calculating the mean
# Visit frequency
df['VisitFrequency'] = LabelEncoder().fit_transform(df['VisitFrequency'])
visit = df.groupby('cluster_num')['VisitFrequency'].mean()
visit = visit.to_frame().reset_index()
visit
cluster_num	VisitFrequency
0	0	2.547988
1	1	2.584483
2	2	2.822368
3	3	2.654472
# Like
df['Like'] = LabelEncoder().fit_transform(df['Like'])
Like = df.groupby('cluster_num')['Like'].mean()
Like = Like.to_frame().reset_index()
Like
cluster_num	Like
0	0	3.275542
1	1	2.962069
2	2	6.171053
3	3	7.422764
# Gender
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
Gender = df.groupby('cluster_num')['Gender'].mean()
Gender = Gender.to_frame().reset_index()
Gender
cluster_num	Gender
0	0	0.523220
1	1	0.398276
2	2	0.411184
3	3	0.569106
segment = Gender.merge(Like, on='cluster_num', how='left').merge(visit, on='cluster_num', how='left')
segment
cluster_num	Gender	Like	VisitFrequency
0	0	0.523220	3.275542	2.547988
1	1	0.398276	2.962069	2.584483
2	2	0.411184	6.171053	2.822368
3	3	0.569106	7.422764	2.654472
# Target segments

plt.figure(figsize = (9,4))
sns.scatterplot(x = "VisitFrequency", y = "Like",data=segment,s=400, color="r")
plt.title("Simple segment evaluation plot for the fast food data set",
          fontsize = 15) 
plt.xlabel("Visit", fontsize = 12) 
plt.ylabel("Like", fontsize = 12) 
plt.show()
